#!/bin/bash
./cmsLoadPkg.sh CLHEP Math
./cmsLoadPkg.sh CondCore DBCommon
./cmsLoadPkg.sh Configuration EventContent
./cmsLoadPkg.sh Configuration Geometry
./cmsLoadPkg.sh Configuration StandardSequences
./cmsLoadPkg.sh DataFormats CLHEP
./cmsLoadPkg.sh DataFormats Common
./cmsLoadPkg.sh DataFormats EcalRecHit
./cmsLoadPkg.sh DataFormats EgammaCandidates
./cmsLoadPkg.sh DataFormats FWLite
./cmsLoadPkg.sh DataFormats GeometryVector
./cmsLoadPkg.sh DataFormats HcalRecHit
./cmsLoadPkg.sh DataFormats JetReco
./cmsLoadPkg.sh DataFormats Math
./cmsLoadPkg.sh DataFormats METReco
./cmsLoadPkg.sh DataFormats MuonReco
./cmsLoadPkg.sh DataFormats TrackCandidate
./cmsLoadPkg.sh DataFormats TrackReco
./cmsLoadPkg.sh FWCore Framework
./cmsLoadPkg.sh FWCore MessageService
./cmsLoadPkg.sh Geometry CaloGeometry
./cmsLoadPkg.sh Geometry Records
./cmsLoadPkg.sh MagneticField Engine
./cmsLoadPkg.sh RecoLocalTracker Configuration
./cmsLoadPkg.sh RecoTracker Configuration
./cmsLoadPkg.sh RecoTracker TrackProducer
./cmsLoadPkg.sh RecoVertex BeamSpotProducer
./cmsLoadPkg.sh RecoPixelVertexing PixelTrackFitting
